name: Publish on Docker Hub and Deploy

on:
  release:
    types: [published]

jobs:
  build_and_pub:
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to Docker
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u $LOGIN --password-stdin
      - uses: actions/checkout@master
      -
      name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        secrets: |
          "TOKEN=${{ secrets.TOKEN_DEV }}"


#  deploy:
#    needs: [build_and_pub]
#    runs-on: [ubuntu-latest]
#    steps:
#      - name: Set tag to env
#        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
